
name: Flutter Windows Build
on:
  push:
    branches: [ main ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Windows bundle
        run: flutter build windows --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pro-windows
          path: build/windows/runner/Release/
